CREATE TABLE goals (
    GOAL_ID VARCHAR,
	MATCH_ID VARCHAR,
	PID	VARCHAR,
	DURATION INT,	
	ASSIST VARCHAR,	
	GOAL_DESC VARCHAR);
COPY goals
FROM 'C:\Program Files\PostgreSQL\17\import\Module project\goals.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE Matches ( 
MATCH_ID VARCHAR,
SEASON VARCHAR,
DATE VARCHAR,
HOME_TEAM VARCHAR,
AWAY_TEAM VARCHAR,
STADIUM	VARCHAR,
HOME_TEAM_SCORE	INT,
AWAY_TEAM_SCORE	INT,
PENALTY_SHOOT_OUT INT,
ATTENDANCE INT);

COPY Matches
FROM 'C:\Program Files\PostgreSQL\17\import\Module project\Matches.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE Players ( 
PLAYER_ID VARCHAR,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
NATIONALITY VARCHAR,
DOB	DATE,
TEAM VARCHAR,
JERSEY_NUMBER REAL,
POSITION VARCHAR,
HEIGHT	REAL,
WEIGHT	REAL,
FOOT VARCHAR
);

COPY Players
FROM 'C:\Program Files\PostgreSQL\17\import\Module project\Players.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE Stadiums ( NAME VARCHAR,
CITY VARCHAR,
COUNTRY VARCHAR,
CAPACITY INT);

COPY Stadiums
FROM 'C:\Program Files\PostgreSQL\17\import\Module project\Stadiums.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE Teams ( TEAM_NAME	VARCHAR,
COUNTRY	VARCHAR,
HOME_STADIUM VARCHAR);

COPY Teams
FROM 'C:\Program Files\PostgreSQL\17\import\Module project\Teams.csv' DELIMITER ',' CSV HEADER;
		